version: '3'

services: 

  app:
    build: 
      context: .
      dockerfile: .docker/node/Dockerfile
    container_name: app
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s node index.js
    networks: 
      - node-network
    tty: true
    depends_on: 
       - mysql
  
  nginx:
    build: 
      context: .docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    entrypoint: dockerize -wait tcp://app:3000 -timeout 20s nginx -g "daemon off;"
    restart: always
    tty: true
    ports: 
      - "8080:80"
    networks: 
      - node-network
    depends_on: 
      - app

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes: 
      - .docker/mysql/data:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge